### ISSUE TITLE
Problem with "org always wins" if org file unsaved.

### ISSUE THREAD

**Issue by svictor9** [dengste/org-caldav#136]
Hi, and thanks for org-caldav! 
It works great for me, but I keep getting myself in the following situation:
1. I call `org-caldav-sync` 
2. org-caldav opens my org files as buffers and writes to them new events from the remote calendar.
3. I forget to save those buffers before I close emacs (or the computer crashes).
4. Next time I run `org-caldav-sync`, it sees that the new events are not in my org file. It then thinks that I deleted them. 
5. As "org always wins", the only option org-caldav offers me from now on is to delete the remote events. I answer "no", but it keeps asking the same question every time I run `org-caldav-sync`.

I want to keep the remote events (which I did not actually delete — the buffer was simply not saved).
Did I overlook an easy way to do that?

**Comment by grauschnabel** [comment]
2 ideas. 1. Create a custom function which saves the files after sync. 2. Remove the org-caldav sync state files, so it forgets everything, and starts new.

There is a third way by editing the sync state files, but I don't recommend this.

-- 
Mag. Martin Kaffanke
+43 650 4514224
http://www.kaffanke.at

-----Original Message-----

**Comment by svictor9** [comment]
Thanks grauschnabel. Indeed, removing sync state files makes org-caldav forget everything. But then on next sync it duplicates all my org entries to the remote calendar, where they already are.
I actually managed to sort this mess out a couple of times by editing the sync state files. It was a rather tedious process though. 
Writing a custom function to save the files after sync would make sense. It would take me some time though as I have no knowledge in lisp. I wonder why it’s not the default behavior of org-caldav anyway.

**Comment by svictor9** [comment]
Sorry, I was wrong: deleting the sync state file does _not_ result in duplicates on the server.

I thought this because on next sync org-caldav was saying "putting event 1 of 639". This made me fear that would duplicate everything and I stopped the process. But actually, letting it run the result is fine. 
This solved my problem for tonight. Thanks for pointing me into this direction.

**Comment by grauschnabel** [comment]
org-caldav does only compare the ID of the org entry and the ID of the server entry.  So you dont get duplicates but it has to override all entries, if you delete the sync state files, thats why it puts all events that exist on the server up once again, because other fields like title, time and so on are not compared, and org wins.  Sync from remote does only happen if the ID does not exist in the org-mode files, or if they have changed on the server but therefore the sync state files are needed.

I'm sure there are reasons why the buffers are not automatically saved after sync.  but as a workarround for you:
```
(defun my-org-caldav-sync ()
  "Save after sync if changed."
  (interactive)
  (org-caldav-sync)
  (save-some-buffers))
```
`(save-some-buffers)` is the same as `C-x s`, so you will be asked, but you dont forget to save.

**Comment by svictor9** [comment]
Thank you for the explanation and for the function. It’s easier than I figured, and works like a charm.
