### ISSUE TITLE
Extremely slow sync since several weeks

### ISSUE THREAD

**Issue by inglada** [dengste/org-caldav#195]
Hi,
I've been using org-caldav for several years now, an although sync was not fast, it was perfect for me. So thank you very much for this package.

For several weeks now I have been having extremely slow syncs. This does not seem to be a caldav server issue, since emacs is running at 100% CPU during sync. 

After profiling, I understand that the org-id-find function is consuming a lot of time. I also have warnings about duplicate IDs (which I already had before but seemed harmful, since they were in ~/.emacs.d/org-caldav-backup.org).

Is there anything I can do to speed up things?

I am using org-caldav-20191024.724 from MELPA. 

Thanks.

**Comment by dengste** [comment]
I'm guessing this happens due to some change in org-id, not in org-caldav. I actually just realized yesterday that the tests are also broken because org-id-find does no longer consider currently open buffers, but this should actually make org-id faster.
So my guess is this happened to you after an org-mode update. If you'd be able to pinpoint this further through profiling, or maybe bisecting org-id.el, this would be very helpful.

**Comment by inglada** [comment]
Hi,
I just upgraded org (updated on melpa 2 days ago) and everything's good again. So I guess this can be closed.
Thanks

**Comment by dengste** [comment]
Thanks for the feedback!

**Comment by inglada** [comment]
Hi,
Unfortunately, the problem is still there. There were a couple of syncs which worked OK, but it is again taking long time.
The events are retrived from the server and the "inbox" files are correctly populated. Since I only do a cal->org sync, that would be enough for me. 
Another info which may be useful is that my org-id-locations file has about 345K entries.
