### ISSUE TITLE
Please, add a non-interactive version

### ISSUE THREAD

**Issue by vanicat** [dengste/org-caldav#81]
I was trying to use async for org-caldav, but there was a problem I couldn't easily solve: caldav ask several question when running (for deleting, for saving some file...). A fully non-interactive version of org-caldav would be very interesting.

Thanks

**Comment by dengste** [comment]
You can set org-caldav-delete-org-entries to 'always or 'never, depending on what you like better. In any case it doesn't ask anymore regarding deletions of Org entries.
What else is being asked?

**Comment by ddoherty03** [comment]
I almost always get a message that says the prior sync aborted, would I like to resume?  I want to always say yes.  But the prompt comes up in a GUI dialog box that blocks emacs.

This keeps me from syncing with run-at-time, which is what I want to do.  I don't want to think about syncing, just do it every 10 minutes or so.

Could add a variable like org-caldav-resume that could be set to 'prompt or 'always or 'never so that I can avoid the prompt?

Thanks for org-caldav, BTW.  It's the best solution I've found for getting my calendar onto my cell phone.

**Comment by dengste** [comment]
Added in d994f83024e23343585ef63f1acd45add40f058e.

**Comment by dengste** [comment]
And with that I mean 14af011c63b1d5446d769882acafb4cd1157e90a ...

**Comment by ddoherty03** [comment]
Much thanks @dengste, that's a big help.
